apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edtroleis
  namespace: apps
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: edtroleis
    repoURL: "https://github.com/edtroleis/argocd.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true